language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script:  ./runtests.sh
