language: python
env:
  - TOX_ENV=py36-django11
  - TOX_ENV=py36-django10
  - TOX_ENV=py35-django11
  - TOX_ENV=py35-django10
  - TOX_ENV=py35-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py34-django10
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django18
  - TOX_ENV=py27-django10
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django18
  - TOX_ENV=pypy-django10
  - TOX_ENV=pypy-django19
  - TOX_ENV=pypy-django18
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
sudo: false
