language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO_INSTALL="Django==1.4.10"
  - DJANGO_INSTALL="Django==1.5.5"
  - DJANGO_INSTALL="Django==1.6.1"
install:
  - pip install -q $DJANGO_INSTALL
  - python setup.py -q install
script:  ./runtests.sh
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_INSTALL="Django==1.4.10"
    - python: "2.6"
      env: DJANGO_INSTALL="Django==1.6.1"
