language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
env:
  - TOX_ENV=py34-django10
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django18
  - TOX_ENV=py27-django10
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django18
  - TOX_ENV=pypy-django10
  - TOX_ENV=pypy-django19
  - TOX_ENV=pypy-django18
  - TOX_ENV=flake8
install:
  - pip install tox
  - pip install tox-travis
script:
  - tox -e $TOX_ENV
sudo: false
